### ISSUE TITLE
kube-prometheus-stack.  prometheus-kube-state-metrics not scraped

### ISSUE THREAD

**Issue by andreadetti** [prometheus-community/helm-charts#1769]
### Describe the bug a clear and concise description of what the bug is.

kube-state-metrics is not scraped because prometheus-kube-state-metrics ServiceMonitor resource does not have the label 'release: prometheus'. I edited it manually with 'kubectl edit' while running and it works.

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack-27.0.1

### What's the chart version?

0.53.1

### What happened?

kube-state-metrics is not scraped 

### What you expected to happen?

kube-state-metrics scraped 

### How to reproduce it?

Install the helm chart. Access Prometheus from the browser. The 'kube_pod_container_resource_requests' should be not available because kube-state-metrics is not scraped.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

curl http://<prometheus_url>/api/v1/query?query="kube_pod_container_resource_requests"

**Comment by monotek** [comment]
Please update to most recent version.

**Comment by dotdc** [comment]
Hi @andreadetti 
Like @monotek said, this should be fixed by: https://github.com/prometheus-community/helm-charts/pull/1683 and https://github.com/prometheus-community/helm-charts/pull/1692

Can you confirm it's working after updating the chart and values to 30.x.x+?

**Comment by peppermor** [comment]
Hi @dotdc we are using latest chart and values but nothing changed still do not work

**Comment by peppermor** [comment]
@dotdc 
```
helm version: version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
kubernetes version: 1.19
kube-state-metrics chart version: 4.4.3
kube-prometheus-stack chart version: 32.0.2
And also:

the result of helm get values ${kube-prometheus-stack-release} (clean your secrets if any)


alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_auth_password: filtered
      smtp_auth_username: filtered
      smtp_from: alertmanager-dec@example.com
      smtp_smarthost: email-smtp.eu-west-1.amazonaws.com:587
    inhibit_rules:
    - equal:
      - alertname
      - cluster
      - service
      source_match:
        severity: critical
      target_match:
        severity: warning
    receivers:
    - email_configs:
      - send_resolved: true
        to: dummy@example.com
      name: ops-receiver
    - name: "null"
    route:
      group_by:
      - alertname
      - cluster
      - service
      group_interval: 5m
      group_wait: 30s
      receiver: ops-receiver
      repeat_interval: 12h
  enabled: true
  ingress:
    enabled: true
    externalUrl: https://dec-alert.example.com
    hosts:
    - dec-alert.example.com
    labels: {}
    pathType: ImplementationSpecific
    paths: []
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: gp2
    tls:
    - hosts:
      - dec-alert.example.com
      secretName: ingress-tls-prometheus
commonLabels:
  cluster: clustername1 :)
  monitoring: prometheus
defaultRules:
  create: false
fullnameOverride: prometheus
global:
  rbac:
    create: true
    pspEnabled: false
grafana:
  enabled: false
kube-state-metrics:
  podSecurityPolicy:
    enabled: false
  prometheus:
    monitor:
      enabled: true
  rbac:
    create: true
  releaseLabel: true
kubeControllerManager:
  enabled: true
  service:
    port: 10252
    selector:
      k8s-app: kube-controller-manager
    targetPort: 10252
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: true
  service:
    port: 10251
    selector:
      k8s-app: kube-scheduler
    targetPort: 10251
kubeStateMetrics:
  enabled: true
kubelet:
  enabled: true
  serviceMonitor:
    https: false
nameOverride: ""
prometheus:
  ingress:
    enabled: true
    hosts:
    - dec-prom.example.com
    labels: {}
    pathType: ImplementationSpecific
    paths: []
    tls:
    - hosts:
      - dec-prom.example.com
      secretName: ingress-tls-prometheus
  prometheusSpec:
    additionalScrapeConfigs:
    [...]
    enableAdminAPI: true
    externalLabels:
      cluster: clustername1 :)
    externalUrl: https://example.com :)
    replicas: 1
    retention: 31d
    retentionSize: 50GB
    ruleSelector:
      matchExpressions:
      - key: prometheus
        operator: In
        values:
        - apache-exporter-rules
        - blackbox-exporter-rules
        - cAdvisor-rules
        - consul-exporter-rules
        - coredns-rules
        - elasticsearch-exporter-rules
        - etcd-rules
        - haproxy-exporter-rules
        - kube-state-metrics-rules
        - mongodb-exporter-rules
        - mysqld-exporter-rules
        - network-rules
        - nginx-exporter-rules
        - node-exporter-rules
        - postgresql-exporter-rules
        - prometheus-rules
        - rabbitmq-exporter-rules
        - redis-exporter-rules
        - rook-rules
        - systemd-rules
        - thanos-rules
        - traefik-exporter-rules
        - wmi-exporter-rules
    serviceMonitorSelector:
      matchLabels:
        monitoring: prometheus
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 60Gi
          storageClassName: gp2
    thanos:
      baseImage: quay.io/thanos/thanos
      objectStorageConfig:
        key: object-store.yaml
        name: thanos
      version: v0.24.0
prometheusOperator:
  admissionWebhooks:
    enabled: false
  configReloaderCpu: 200m
  enabled: false




the result of kubectl get servicemonitors.monitoring.coreos.com -n monitoring kube-prometheus-stack-kube-state-metrics -o yaml (change namespace, release name if needed)

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
  creationTimestamp: "2021-09-27T12:14:35Z"
  generation: 1
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/version: 2.3.0
    helm.sh/chart: kube-state-metrics-4.4.3
    release: prometheus
  name: prometheus-kube-state-metrics
  namespace: prometheus
  resourceVersion: "233982310"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/prometheus/servicemonitors/prometheus-kube-state-metrics
  uid: 98005d32-9e0b-410d-988a-2d2efdb9baaa
spec:
  endpoints:
  - honorLabels: true
    port: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/name: kube-state-metrics

```

**Comment by dotdc** [comment]
@peppermor 

It looks like you use the `monitoring: prometheus` label as the `serviceMonitorSelector`:
```
    serviceMonitorSelector:
      matchLabels:
        monitoring: prometheus
```
 
Since your `kube-state-metrics` ServiceMonitor doesn't have this label, it is not scrapped.

 To fix the problem you can either:
 - Switch back to the default `release` label
 - Or you could add your extra label to kube-state-metrics:
```
 kube-state-metrics:
  prometheus:
    monitor:
      enabled: true
      additionalLabels:
        monitoring: prometheus
```

**Comment by peppermor** [comment]
Thank you very much @dotdc for pointing us to obvious mistake we did ::facepalm::

**Comment by dotdc** [comment]
Great, closing this then :+1:

**Comment by ogechivivian** [comment]
@dotdc  I facing similar issue, using helm chart + argocd. I have updated values.yaml file to include   
kube-state-metrics:
    prometheus:
      monitor:
        enabled: true
        additionalLabels:
          release: prometheus

**Comment by dotdc** [comment]
Hi @ogechivivian,

The `release:` label value must match the release name of your kube-prometheus-stack helm deployment.
Default should be `release: kube-prometheus-stack`.

You can check the value in your kube-state-metrics pod with this command: 

```
pod="$(kubectl get po -n monitoring | awk '/kube-state-metrics/{ print $1 }')"
kubectl get po -n monitoring "${pod}" -o yaml | grep release
```

**Comment by ogechivivian** [comment]
Hi @dotdc ,

Thanks  executed the command and I can confirm the release is prometheus
$ kubectl get po -n monitoring "${pod}" -o yaml | grep release
    release: prometheus

**Comment by dotdc** [comment]
Must be a configuration problem, you should try with the latest version of the chart with default values (and slowly customize it).

**Comment by ogechivivian** [comment]
@dotdc  thanks for the support it was a mismatch label between the servicemonitor and service. Using  selectorOverride fixed it https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/troubleshooting.md#troubleshooting-servicemonitor-changes

**Comment by kenske** [comment]
@ogechivivian By default, ArgoCD will update the `instance` label to match the app name. Follow these docs to have ArgoCD use an alternate label: https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-app-out-of-sync-even-after-syncing

**Comment by lemonzst** [comment]
Adding to what @kenske mentioned: What you are experienced is most probably due to a difference between the Argo CD application name and the Helm release name. Since the value of the "app.kubernetes.io/instance" label in the kube-prometheus-stack is derived from the Helm Release name, whereas in argo it is derived for the Argo CD application name, Argo CD overwrites the values of the "app.kubernetes.io/instance" labels. However, since the selectors (for example in ServiceMonitors) are not overwritten they are referencing the no-longer existing labels. (Hence kube-state-metrics not scraped). 

I opened [this proposal](https://github.com/argoproj/argo-cd/issues/18411) to address the issue.

**Comment by Kienan6** [comment]
This thread resolved my issue when deploying the stack with argo. Thank you.
