### ISSUE TITLE
[kube-prometheus-stack] Unable to install the kube-prometheus-stack helm chart with default values.yaml file on Openshift 4.12 in the user defined namespace

### ISSUE THREAD

**Issue by sbhosle-tibco** [prometheus-community/helm-charts#3370]
### Describe the bug a clear and concise description of what the bug is.

While trying to install Kube-prometheus-stack helm chart on OpenShift 4.12 with default values.yaml file in the user defined namespace I see an error such as 
```
Error: INSTALLATION FAILED: failed pre-install: timed out waiting for the condition
helm.go:84: [debug] failed pre-install: timed out waiting for the condition
INSTALLATION FAILED

``` 

### What's your helm version?

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-15T02:14:53Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v5.0.1 Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.8+27e744f", GitCommit:"df8a1b9c3feb33a5ba9d3f0b80fce83a1e301859", GitTreeState:"clean", BuildDate:"2023-04-06T20:23:55Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

45.27.1

### What happened?

Here's the output of the helm install command that's failing
```shell
$ helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --debug --namespace demo
install.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: /home/sachin/.cache/helm/repository/kube-prometheus-stack-45.27.1.tgz

client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 1 resource(s)
install.go:165: [debug] Clearing discovery cache
wait.go:66: [debug] beginning wait for 8 resources with timeout of 1m0s
client.go:310: [debug] Starting delete for "kube-prometheus-stack-admission" ServiceAccount
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "kube-prometheus-stack-admission" ClusterRole
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "kube-prometheus-stack-admission" ClusterRoleBinding
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "kube-prometheus-stack-admission" Role
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "kube-prometheus-stack-admission" RoleBinding
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "kube-prometheus-stack-admission-create" Job
client.go:128: [debug] creating 1 resource(s)
W0512 14:12:03.183784  151042 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "create" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "create" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "create" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
client.go:540: [debug] Watching for changes to Job kube-prometheus-stack-admission-create with timeout of 5m0s
client.go:568: [debug] Add/Modify event for kube-prometheus-stack-admission-create: ADDED
client.go:607: [debug] kube-prometheus-stack-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for kube-prometheus-stack-admission-create: MODIFIED
client.go:607: [debug] kube-prometheus-stack-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Error: INSTALLATION FAILED: failed pre-install: timed out waiting for the condition
helm.go:84: [debug] failed pre-install: timed out waiting for the condition
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:141
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1571
``` 
I see an error in the K8s job kube-prometheus-stack-admission-create events
```
Error creating: pods "kube-prometheus-stack-admission-create-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 2000: must be in the ranges: [1000710000, 1000719999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "kube-prometheus-stack-scc": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
``` 

### What you expected to happen?

I expect that the helm chart kube-prometheus-stack be installed with the default values.yaml file just as it gets installed in AKS and EKS cloud platforms.

### How to reproduce it?

Pre-requisite

1. Openshift 4.12 cluster
2. Kubectl installed
3. Helm v3 installed

Follow the below steps to reproduce

1. Create a user defined namespace such as demo
```shell
$ kubectl create namespace demo
``` 
2. Execute below commands to install the kube-prometheus-stack helm chart in the demo namespace
```shell
$ helm repo add prometheus-community https://prometheus-community.github.io/helm-charts 
$ helm repo update
$ helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --debug --namespace demo
``` 

### Enter the command that you execute and failing/misfunctioning.

```shell
helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --debug  --namespace demo
```

**Comment by QuentinBisson** [comment]
@sbhosle-tibco I think this was solved in https://github.com/prometheus-community/helm-charts/commit/6be7a82ea5c0f966ce4d0c13e91a7edae98a857c Could you try and let me know?

**Comment by sbhosle-tibco** [comment]
@QuentinBisson Thanks, I tried with kube-prometheus-stack version 46.3.0 but still I see the same issue. The k8s job named "kube-prometheus-stack-admission-create" is still failing with the below error

`
Error creating: pods "kube-prometheus-stack-admission-create-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 2000: must be in the ranges: [1000700000, 1000709999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount, provider "privileged-genevalogging": Forbidden: not usable by user or serviceaccount]
`

**Comment by zeritti** [comment]
There is no way to deploy the chart with the default values in a common OCP v4 cluster since it sets specific conditions and requirements on workloads. 
As you see in the error, the [SCC](https://docs.openshift.com/container-platform/4.12/authentication/managing-security-context-constraints.html) admission controller attempts to apply an available SCC (anyuid, restricted, nonroot, etc.) but for the given `securityContext`s as set in the manifests through the default values _and_ the specific serviceaccount, it does not find a matching SCC allowing those settings and hence, the workload is not admitted.

You can also see that UID and GID as set in the security contexts must come from the range defined for your project (shown in the error output). Setting `runAsUser`, `runAsGroup` and `fsGroup` to values from that range would be required. This is what you might wish to do with the create and patch jobs' values next.

Most of the workloads should be able to run with the default SCC `restricted-v2` (probably not without some adjustments in their security contexts as mentioned above).

**Comment by samyak335** [comment]
Is this issue resolved , i am observing same issue, what settings/needs to be done to resolve this?

**Comment by pfeifferj** [comment]
this issue is still current

```bash
❯ helm search repo -l prometheus-stack | head
NAME                                                    CHART VERSION   APP VERSION     DESCRIPTION
prometheus-community/kube-prometheus-stack              65.5.1          v0.77.2         kube-prometheus-stack collects Kubernetes manif...
prometheus-community/kube-prometheus-stack              65.5.0          v0.77.2         kube-prometheus-stack collects Kubernetes manif...
prometheus-community/kube-prometheus-stack              65.4.0          v0.77.1         kube-prometheus-stack collects Kubernetes manif...
prometheus-community/kube-prometheus-stack              65.3.2          v0.77.1         kube-prometheus-stack collects Kubernetes manif...
prometheus-community/kube-prometheus-stack              65.3.1          v0.77.1         kube-prometheus-stack collects Kubernetes manif...
prometheus-community/kube-prometheus-stack              65.3.0          v0.77.1         kube-prometheus-stack collects Kubernetes manif...
prometheus-community/kube-prometheus-stack              65.2.0          v0.77.1         kube-prometheus-stack collects Kubernetes manif...
prometheus-community/kube-prometheus-stack              65.1.1          v0.77.1         kube-prometheus-stack collects Kubernetes manif...
prometheus-community/kube-prometheus-stack              65.1.0          v0.77.1         kube-prometheus-stack collects Kubernetes manif...
❯ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.17.0    True        False         18d     
```

```
Error creating: pods "prometheus-operator-kube-p-admission-create-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .containers[0].runAsUser: Invalid value: 2000: must be in the ranges: [1000750000, 1000759999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```

**Comment by NSH4RPY** [comment]
Ive been seeing this issue as well, has anyone managed to work round it?
